# Generated by Django 5.0.6 on 2026-06-25 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignerTailor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('specialty', models.CharField(blank=True, max_length=120)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_text', models.TextField(help_text="Her open description — 'no detail is too small'.")),
                ('mood_tags', models.JSONField(blank=True, default=list, help_text='List of MoodTag values, optional.')),
                ('occasion_tag', models.CharField(blank=True, choices=[('everyday', 'Everyday'), ('celebration', 'Celebration'), ('travel', 'Travel'), ('just_for_me', 'Just for me')], max_length=20)),
                ('feeling_prompt', models.CharField(blank=True, help_text="Answer to 'What feeling do you want this outfit to give you?'", max_length=300)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_review', 'In review'), ('in_progress', 'In progress'), ('delivered_to_dreamer', 'Delivered to dreamer'), ('live', 'Live'), ('declined_paused', 'Declined / paused')], default='submitted', max_length=24)),
                ('consent_to_publish', models.BooleanField(default=False, help_text='Defaults False. Only set True via the dedicated consent endpoint — never via generic PATCH.')),
                ('consent_requested_at', models.DateTimeField(blank=True, null=True)),
                ('consent_granted_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_designer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_dreams', to='dreams.designertailor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dreams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DreamInspirationImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspiration_images', to='dreams.dream')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DreamStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage_name', models.CharField(help_text='e.g. Brief received, Fabric/pattern selected, In production, Quality check, Shipped. Confirm actual taxonomy against real ops — see PRD Open Decision #5.', max_length=80)),
                ('photo_url', models.URLField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('dream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='dreams.dream')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
