# Generated by Django 5.0.6 on 2026-06-25 08:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dreams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField()),
                ('headline', models.CharField(blank=True, max_length=140)),
                ('deep_link', models.CharField(blank=True, max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('kurti', 'Kurti'), ('top', 'Top'), ('dress', 'Dress'), ('co_ord_set', 'Co-ord set')], max_length=20)),
                ('mood_tags', models.JSONField(blank=True, default=list, help_text='List of MoodTag values for filtering.')),
                ('price_inr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customer_photo_url', models.URLField(blank=True, help_text='Preferred — real customer wearing the piece, per brand authenticity rule.')),
                ('model_photo_url', models.URLField(blank=True, help_text='Fallback only, per PRD Section 7.1.')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_publishable', models.BooleanField(default=False, help_text='Gate enforced in services.py — see dreamer-first-delivery rule.')),
                ('delivery_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('love_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('origin_dream', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='dreams.dream')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
