# Generated by Django 5.0.6 on 2026-06-25 08:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('dream_status', 'Dream status update'), ('new_arrival', 'New arrival matching saved moods'), ('wishlist_reminder', 'Wishlist reminder'), ('shipping_update', 'Shipping update'), ('social_proof', 'Social proof (X women loved your idea)')], max_length=24)),
                ('body', models.CharField(help_text='Must pass the calm-tone check in services.py before saving — see architecture doc Section 8.2.', max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
